"""Recompile every area overlay as its own unit for PS2Recomp's runtime.

    python tools/recomp/ovl_recomp.py --recomp D:/Tools/PS2Recomp/out/mingw/ps2xRecomp/ps2_recomp.exe \
        --runtime D:/Tools/PS2Recomp-ext/ps2xRuntime

Inputs, per overlay AREAnn:
  build/disc/OVERLAY/AREAnn.BIN      the MWo3 file (number, text range)
  build/ghidra/ov/AREAnn.elf         the overlay wrapped with the executable
  build/recomp/ov/AREAnn.ghidra.csv  its function map (export_overlays.sh)

Every overlay loads to the same address, so the units cannot share names or
one function table. Function names get an `aNN_` prefix; each unit gets a
dense table of its text, registered with ps2RegisterOverlayFunctionTable()
under its overlay number, and the runtime serves the table of the overlay
whose header is in memory. Calls from an overlay into the executable go
through the runtime's dispatcher, as the recompiler emits for targets it
does not know.

Outputs go to <runtime>/src/runner/zz_ovl_*.cpp (named to sort after the
executable's files, so its unity batches stay as they were) and
<runtime>/include/ovl/.
"""
import argparse
import csv
import os
import re
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from ps2kit.mwo3 import Overlay  # noqa: E402

TOML = """[general]
input = "{elf}"
output = "{out}"
ghidra_output = "{csv}"
single_file_output = false
patch_syscalls = false
patch_cop0 = true
patch_cache = true
stubs = []
untracked_stubs = []
skip = []
"""

TABLE = """// Generated by tools/recomp/ovl_recomp.py: function table of {name}
// (overlay {number}, text {base:#x}-{end:#x}).
#include "ps2_runtime.h"
#include "ovl/ps2_overlay_{name}.h"

// Unique names: the unity build may put two tables in one translation unit.
namespace ovl_{name} {{
PS2Runtime::RecompiledFunction table[{slots}u] = {{}};

struct Init {{
    Init() {{
{entries}
        ps2RegisterOverlayFunctionTable({header:#x}u, {number}u, {base:#x}u, {end:#x}u, table);
    }}
}};
const Init init;
}}
"""

ENTRY = re.compile(r"g_ps2RecompiledFunctionTable\[\d+\] = (\w+); // 0x([0-9a-f]+)")
INCLUDE = "#include <ps2_recompiled_functions.h>\n"


def unit(name, root, args):
    ov = Overlay(open(os.path.join(args.disc, "OVERLAY", name + ".BIN"), "rb").read())
    base, end = ov.text_va, ov.text_va + ov.text_size
    prefix = "a%s_" % name[4:].lower()
    work = os.path.join(args.work, name)
    out = os.path.join(work, "out")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(out)

    rows = list(csv.reader(open(os.path.join(args.work, name + ".ghidra.csv"))))
    kept = [r for r in rows[1:] if base <= int(r[1], 16) < end]
    with open(os.path.join(work, name + ".csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(rows[0])
        for r in kept:
            w.writerow([prefix + r[0]] + r[1:])
    toml = os.path.join(work, name + ".toml")
    with open(toml, "w") as f:
        f.write(TOML.format(elf=os.path.abspath(os.path.join(args.elfs, name + ".elf")).replace("\\", "/"),
                            out=os.path.abspath(out).replace("\\", "/"),
                            csv=os.path.abspath(os.path.join(work, name + ".csv")).replace("\\", "/")))
    log = open(os.path.join(work, "recomp.log"), "w")
    rc = subprocess.call([args.recomp, toml], stdout=log, stderr=subprocess.STDOUT)
    if rc:
        print("%s: recompiler exit %d (see %s)" % (name, rc, log.name))

    entries = []
    for line in open(os.path.join(out, "register_functions.cpp")):
        m = ENTRY.search(line)
        if m and base <= int(m.group(2), 16) < end:
            entries.append((int(m.group(2), 16), m.group(1)))

    # Install: the unit's header, its functions, its table.
    runner = os.path.join(root, "src", "runner")
    incdir = os.path.join(root, "include", "ovl")
    os.makedirs(incdir, exist_ok=True)
    # Its own include guard: the executable's header has the generated one.
    header = open(os.path.join(out, "ps2_recompiled_functions.h")).read()
    header = header.replace("PS2_RECOMPILED_FUNCTIONS_H", "PS2_OVERLAY_%s_H" % name)
    open(os.path.join(incdir, "ps2_overlay_%s.h" % name), "w").write(header)
    for old in os.listdir(runner):
        if old.startswith("zz_ovl_%s_" % name.lower()):
            os.remove(os.path.join(runner, old))
    files = 0
    for fn in sorted(os.listdir(out)):
        if not fn.endswith(".cpp") or fn == "register_functions.cpp":
            continue
        src = open(os.path.join(out, fn)).read()
        # The unit's own declarations, besides the executable's.
        src = src.replace(INCLUDE, INCLUDE + '#include "ovl/ps2_overlay_%s.h"\n' % name, 1)
        dst = os.path.join(runner, "zz_ovl_%s_%s" % (name.lower(), fn))
        open(dst, "w").write(src)
        files += 1
    table = "\n".join("        table[%du] = %s; // 0x%x" % ((a - base) >> 2, f, a) for a, f in entries)
    open(os.path.join(runner, "zz_ovl_%s_table.cpp" % name.lower()), "w").write(
        TABLE.format(name=name, number=ov.number, base=base, end=end, slots=(end - base) >> 2,
                     entries=table, header=ov.load))
    print("%s  overlay %2d  text %08X-%08X  %4d records  %4d files  %4d table entries"
          % (name, ov.number, base, end, len(kept), files, len(entries)))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--recomp", required=True, help="ps2_recomp.exe")
    ap.add_argument("--runtime", required=True, help="ps2xRuntime directory to install into")
    ap.add_argument("--disc", default="build/disc")
    ap.add_argument("--elfs", default="build/ghidra/ov")
    ap.add_argument("--work", default="build/recomp/ov")
    ap.add_argument("names", nargs="*", help="AREAnn (default: every exported one)")
    args = ap.parse_args()
    names = args.names or sorted(f[:-len(".ghidra.csv")] for f in os.listdir(args.work)
                                 if f.endswith(".ghidra.csv"))
    for name in names:
        unit(name, args.runtime, args)


if __name__ == "__main__":
    main()
